spring:
  profiles:
    active: local
    include: connection, oauth2

app:
  auth:
    secret-key: ${TOKEN_SECRET_KEY}

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_ACCESS_KEY}
    s3:
      bucket: job-za-bucket
    stack.auto: false
    region:
      static: ap-northeast-2